-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 05:52:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema motorhomedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Nordic_Motorhome` DEFAULT CHARACTER SET utf8 ;
USE `motorhomedb` ;

-- -----------------------------------------------------
-- Table `motorhomedb`.`accesories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motorhomedb`.`accesories` (
  `accessories_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` FLOAT NULL DEFAULT NULL,
  `name` VARCHAR(16) NULL DEFAULT NULL,
  `image_location` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`accessories_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motorhomedb`.`motorhomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motorhomedb`.`motorhomes` (
  `motorhome_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(24) NULL DEFAULT NULL,
  `brand` VARCHAR(16) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `licenseplate` VARCHAR(9) NULL DEFAULT NULL,
  `type` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`motorhome_id`),
  UNIQUE INDEX `licenseplate_UNIQUE` (`licenseplate` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `motorhomedb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motorhomedb`.`contact` (
  `contact_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(24) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(12) NULL DEFAULT NULL,
  PRIMARY KEY (`contact_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8
COMMENT = 'customer or employee table will be related later';


-- -----------------------------------------------------
-- Table `motorhomedb`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motorhomedb`.`reservations` (
  `reservation_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL DEFAULT NULL,
  `kmFromOffice` DOUBLE NULL DEFAULT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  `numberOfDays` INT(11) NULL DEFAULT NULL,
  `motorhome_id` INT(10) NOT NULL,
  `contact_id` INT(10) NOT NULL,
  PRIMARY KEY (`reservation_id`),
ENGINE = InnoDB
AUTO_INCREMENT = 100025
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motorhomedb`.`reservations_has_accessories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motorhomedb`.`reservations_has_accessories` (
  `reservation_id` INT(10) UNSIGNED NOT NULL,
  `accessories_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`reservation_id`, `accessories_id`),
  INDEX `acc_id_idx` (`accessories_id` ASC) VISIBLE,
  INDEX `res_id_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `acc_id`
    FOREIGN KEY (`accessories_id`)
    REFERENCES `motorhomedb`.`accesories` (`accessories_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `res_id`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `motorhomedb`.`reservations` (`reservation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Junction table';


-- -----------------------------------------------------
-- Table `motorhomedb`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motorhomedb`.`sales` (
  `reservation_id` INT(10) UNSIGNED NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `sales_res_id_idx` (`reservation_id` ASC) VISIBLE,
  CONSTRAINT `sales_res_id`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `motorhomedb`.`reservations` (`reservation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `motorhomedb`.`service_states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `motorhomedb`.`service_states` (
  `service_states_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `motorhome_id` INT(10) UNSIGNED NOT NULL,
  `damages` MEDIUMTEXT NULL DEFAULT NULL,
  `oil` FLOAT NULL DEFAULT NULL,
  `water` FLOAT NULL DEFAULT NULL,
  `date_checked` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`service_states_id`),
  INDEX `service_motor_id_idx` (`motorhome_id` ASC) VISIBLE,
  CONSTRAINT `service_motor_id`
    FOREIGN KEY (`motorhome_id`)
    REFERENCES `motorhomedb`.`motorhomes` (`motorhome_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
